In [51]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv("ecommerce_sales_analyzer_dataset.csv")
data

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Payment_Method,Order_Status,Rating
0,1001,2026-04-03,Kiran,Bangalore,Clothing,Jeans,4,1299,Cash on Delivery,Completed,4.6
1,1002,2026-07-22,Anil,Delhi,Clothing,Jeans,3,1299,UPI,Pending,4.2
2,1003,2026-06-07,Rahul,Vijayawada,Electronics,Keyboard,4,1200,Net Banking,Cancelled,NaN
3,1004,2026-07-23,Meena,Hyderabad,Electronics,Bluetooth Speaker,1,2200,UPI,Completed,4.0
4,1005,2026-06-19,Varun,Delhi,Home,Backpack,3,899,Card,Completed,4.9
...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-07-20,Rohit,Mumbai,Home,Backpack,1,899,Net Banking,Completed,3.8
96,1097,2026-02-15,Kavya,Chennai,Home,Water Bottle,5,599,Net Banking,Completed,4.6
97,1098,2026-07-13,Kavya,Chennai,Electronics,Bluetooth Speaker,1,2200,UPI,Completed,4.9
98,1099,2026-04-28,Varun,Hyderabad,Electronics,Bluetooth Speaker,1,2200,Cash on Delivery,Completed,4.0
99,1100,2026-03-04,Nikhil,Pune,Electronics,Bluetooth Speaker,2,2200,UPI,Completed,4.9

In [53]:
print(data.isnull().sum())

Order_ID           0
Order_Date         0
Customer_Name      0
City               0
Category           0
Product            0
Quantity           0
Unit_Price         0
Payment_Method     0
Order_Status       0
Rating            14
dtype: int64

In [54]:
print(data[data["Rating"].isnull()])

    Order_ID  Order_Date Customer_Name        City     Category  \
2       1003  2026-06-07         Rahul  Vijayawada  Electronics
7       1008  2026-02-22         Varun      Mumbai     Clothing
9       1010  2026-05-14         Aisha      Mumbai  Electronics
16      1017  2026-02-02         Sneha     Chennai         Home
18      1019  2026-08-06         Kiran     Chennai  Electronics
24      1025  2026-01-27        Swathi        Pune  Electronics
25      1026  2026-05-17         Sneha   Hyderabad  Electronics
38      1039  2026-05-28        Rakesh  Vijayawada  Electronics
44      1045  2026-02-20        Vikram     Chennai     Clothing
50      1051  2026-03-08         Kavya  Vijayawada        Books
70      1071  2026-04-05         Rahul        Pune         Home
76      1077  2026-03-03         Rohit     Chennai  Electronics
82      1083  2026-08-18         Rohit  Vijayawada         Home
84      1085  2026-03-06        Swathi   Hyderabad     Clothing

           Product  Quantity  Unit_Price    Payment_Method Order_Status  \
2         Keyboard         4        1200       Net Banking    Cancelled
7         Sneakers         2        2499  Cash on Delivery    Completed
9      Smart Watch         2        3500              Card    Cancelled
16       Desk Lamp         2        1199       Net Banking    Cancelled
18  Wireless Mouse         5         650               UPI    Cancelled
24  Wireless Mouse         1         650               UPI    Cancelled
25      Headphones         3        1800  Cash on Delivery    Cancelled
38      Headphones         3        1800       Net Banking    Cancelled
44         T-Shirt         5         499  Cash on Delivery    Cancelled
50  Data Analytics         2         699  Cash on Delivery    Cancelled
70    Water Bottle         4         599  Cash on Delivery    Cancelled
76  Wireless Mouse         1         650  Cash on Delivery    Completed
82       Desk Lamp         1        1199              Card    Cancelled
84          Hoodie         5        1599  Cash on Delivery    Cancelled

    Rating
2      NaN
7      NaN
9      NaN
16     NaN
18     NaN
24     NaN
25     NaN
38     NaN
44     NaN
50     NaN
70     NaN
76     NaN
82     NaN
84     NaN

In [55]:
average_rating = data["Rating"].mean()

print("Average Rating:", average_rating)

Average Rating: 3.980232558139534

In [56]:
data["Rating"] = data["Rating"].fillna(average_rating)
data

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Payment_Method,Order_Status,Rating
0,1001,2026-04-03,Kiran,Bangalore,Clothing,Jeans,4,1299,Cash on Delivery,Completed,4.600000
1,1002,2026-07-22,Anil,Delhi,Clothing,Jeans,3,1299,UPI,Pending,4.200000
2,1003,2026-06-07,Rahul,Vijayawada,Electronics,Keyboard,4,1200,Net Banking,Cancelled,3.980233
3,1004,2026-07-23,Meena,Hyderabad,Electronics,Bluetooth Speaker,1,2200,UPI,Completed,4.000000
4,1005,2026-06-19,Varun,Delhi,Home,Backpack,3,899,Card,Completed,4.900000
...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-07-20,Rohit,Mumbai,Home,Backpack,1,899,Net Banking,Completed,3.800000
96,1097,2026-02-15,Kavya,Chennai,Home,Water Bottle,5,599,Net Banking,Completed,4.600000
97,1098,2026-07-13,Kavya,Chennai,Electronics,Bluetooth Speaker,1,2200,UPI,Completed,4.900000
98,1099,2026-04-28,Varun,Hyderabad,Electronics,Bluetooth Speaker,1,2200,Cash on Delivery,Completed,4.000000
99,1100,2026-03-04,Nikhil,Pune,Electronics,Bluetooth Speaker,2,2200,UPI,Completed,4.900000

In [57]:
print(data.isnull().sum())

Order_ID          0
Order_Date        0
Customer_Name     0
City              0
Category          0
Product           0
Quantity          0
Unit_Price        0
Payment_Method    0
Order_Status      0
Rating            0
dtype: int64

In [58]:
print("Duplicate rows:", data.duplicated().sum())

Duplicate rows: 0

In [59]:
print(data.dtypes)

Order_ID            int64
Order_Date            str
Customer_Name         str
City                  str
Category              str
Product               str
Quantity            int64
Unit_Price          int64
Payment_Method        str
Order_Status          str
Rating            float64
dtype: object

In [60]:
data["Order_Date"] = pd.to_datetime(data["Order_Date"])

print(data.dtypes)

Order_ID                   int64
Order_Date        datetime64[us]
Customer_Name                str
City                         str
Category                     str
Product                      str
Quantity                   int64
Unit_Price                 int64
Payment_Method               str
Order_Status                 str
Rating                   float64
dtype: object

In [61]:
print("First Order Date:", data["Order_Date"].min())
print("Last Order Date:", data["Order_Date"].max())

First Order Date: 2026-01-04 00:00:00
Last Order Date: 2026-08-31 00:00:00

In [62]:
data["Revenue"] = data["Quantity"] * data["Unit_Price"]

data.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Unit_Price,Payment_Method,Order_Status,Rating,Revenue
0,1001,2026-04-03,Kiran,Bangalore,Clothing,Jeans,4,1299,Cash on Delivery,Completed,4.600000,5196
1,1002,2026-07-22,Anil,Delhi,Clothing,Jeans,3,1299,UPI,Pending,4.200000,3897
2,1003,2026-06-07,Rahul,Vijayawada,Electronics,Keyboard,4,1200,Net Banking,Cancelled,3.980233,4800
3,1004,2026-07-23,Meena,Hyderabad,Electronics,Bluetooth Speaker,1,2200,UPI,Completed,4.000000,2200
4,1005,2026-06-19,Varun,Delhi,Home,Backpack,3,899,Card,Completed,4.900000,2697

In [63]:
print(data[["Quantity", "Unit_Price", "Revenue"]])

    Quantity  Unit_Price  Revenue
0          4        1299     5196
1          3        1299     3897
2          4        1200     4800
3          1        2200     2200
4          3         899     2697
..       ...         ...      ...
95         1         899      899
96         5         599     2995
97         1        2200     2200
98         1        2200     2200
99         2        2200     4400

[100 rows x 3 columns]

In [64]:
total_revenue = data["Revenue"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 370628

In [65]:
average_order_value = data["Revenue"].mean()

print("Average Order Value:", average_order_value)

Average Order Value: 3706.28

In [66]:
highest_order = data.loc[data["Revenue"].idxmax()]

print(highest_order)

Order_ID                         1034
Order_Date        2026-07-06 00:00:00
Customer_Name                    Anil
City                         Warangal
Category                  Electronics
Product                   Smart Watch
Quantity                            4
Unit_Price                       3500
Payment_Method       Cash on Delivery
Order_Status                Completed
Rating                            3.0
Revenue                         14000
Name: 33, dtype: object

In [67]:
lowest_order = data.loc[data["Revenue"].idxmin()]

print(lowest_order)

Order_ID                         1049
Order_Date        2026-02-15 00:00:00
Customer_Name                  Rakesh
City                           Mumbai
Category                         Home
Product                  Water Bottle
Quantity                            1
Unit_Price                        599
Payment_Method       Cash on Delivery
Order_Status                  Pending
Rating                            4.1
Revenue                           599
Name: 48, dtype: object

In [68]:
product_sales = data.groupby("Product")["Revenue"].sum()

print(product_sales)

Product
Backpack               4495
Bluetooth Speaker     33000
Coffee Mug             3588
Data Analytics        11883
Desk Lamp             20383
Headphones            19800
Hoodie                49569
Jeans                 22083
Keyboard              26400
Python Programming    15980
Smart Watch           45500
Sneakers              42483
T-Shirt               10479
Water Bottle          26356
Web Development       17829
Wireless Mouse        20800
Name: Revenue, dtype: int64

In [69]:
product_sales = product_sales.sort_values(ascending=False)

print(product_sales)

Product
Hoodie                49569
Smart Watch           45500
Sneakers              42483
Bluetooth Speaker     33000
Keyboard              26400
Water Bottle          26356
Jeans                 22083
Wireless Mouse        20800
Desk Lamp             20383
Headphones            19800
Web Development       17829
Python Programming    15980
Data Analytics        11883
T-Shirt               10479
Backpack               4495
Coffee Mug             3588
Name: Revenue, dtype: int64

In [70]:
category_sales = data.groupby("Category")["Revenue"].sum()

print(category_sales)

Category
Books           45692
Clothing       124614
Electronics    145500
Home            54822
Name: Revenue, dtype: int64

In [71]:
category_sales = data.groupby("Category")["Revenue"].sum()

print(category_sales)

Category
Books           45692
Clothing       124614
Electronics    145500
Home            54822
Name: Revenue, dtype: int64

In [72]:
customer_sales = data.groupby("Customer_Name")["Revenue"].sum()

print(customer_sales)

Customer_Name
Aditya     7499
Aisha     29046
Anil      49030
Divya     14890
Kavya     24081
Kiran     31440
Meena     11341
Neha      11580
Nikhil    16783
Pooja      7994
Priya     23980
Rahul     15337
Rakesh    24790
Rohit     11592
Sanjay    11592
Sneha     31537
Swathi    11940
Varun     24886
Vikram    11290
Name: Revenue, dtype: int64

In [73]:
customer_sales = customer_sales.sort_values(ascending=False)

print(customer_sales)

Customer_Name
Anil      49030
Sneha     31537
Kiran     31440
Aisha     29046
Varun     24886
Rakesh    24790
Kavya     24081
Priya     23980
Nikhil    16783
Rahul     15337
Divya     14890
Swathi    11940
Rohit     11592
Sanjay    11592
Neha      11580
Meena     11341
Vikram    11290
Pooja      7994
Aditya     7499
Name: Revenue, dtype: int64

In [74]:
city_sales = data.groupby("City")["Revenue"].sum()

print(city_sales)

City
Bangalore     69259
Chennai       43525
Delhi         31429
Hyderabad     67416
Mumbai        32065
Pune          49368
Vijayawada    29791
Warangal      47775
Name: Revenue, dtype: int64

In [75]:
city_sales = data.groupby("City")["Revenue"].sum()

print(city_sales)

City
Bangalore     69259
Chennai       43525
Delhi         31429
Hyderabad     67416
Mumbai        32065
Pune          49368
Vijayawada    29791
Warangal      47775
Name: Revenue, dtype: int64

In [76]:
print(data["Order_Status"].value_counts())

Order_Status
Completed    69
Pending      19
Cancelled    12
Name: count, dtype: int64

In [77]:
print(data["Payment_Method"].value_counts())

Payment_Method
Cash on Delivery    34
Net Banking         26
UPI                 25
Card                15
Name: count, dtype: int64

In [78]:
category_rating = data.groupby("Category")["Rating"].mean()

print(category_rating)

Category
Books          3.914749
Clothing       3.928488
Electronics    3.953601
Home           4.122529
Name: Rating, dtype: float64

In [79]:
data["Month"] = data["Order_Date"].dt.month

print(data[["Order_Date", "Month"]].head())

  Order_Date  Month
0 2026-04-03      4
1 2026-07-22      7
2 2026-06-07      6
3 2026-07-23      7
4 2026-06-19      6

In [80]:
monthly_sales = data.groupby("Month")["Revenue"].sum()

print(monthly_sales)

Month
1    37918
2    36962
3    51618
4    34531
5    66029
6    41924
7    52418
8    49228
Name: Revenue, dtype: int64

In [81]:
data["Month_Name"] = data["Order_Date"].dt.strftime("%B")

print(data[["Order_Date", "Month_Name"]].head())

  Order_Date Month_Name
0 2026-04-03      April
1 2026-07-22       July
2 2026-06-07       June
3 2026-07-23       July
4 2026-06-19       June

In [82]:
monthly_sales = data.groupby("Month_Name")["Revenue"].sum()

print(monthly_sales)

Month_Name
April       34531
August      49228
February    36962
January     37918
July        52418
June        41924
March       51618
May         66029
Name: Revenue, dtype: int64

In [83]:
category_analysis = data.groupby("Category").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Average_Price=("Unit_Price", "mean"),
    Average_Rating=("Rating", "mean")
)

print(category_analysis)

             Total_Revenue  Total_Quantity  Average_Price  Average_Rating
Category
Books                45692              58     791.105263        3.914749
Clothing            124614              86    1529.769231        3.928488
Electronics         145500              93    1677.419355        3.953601
Home                 54822              78     749.000000        4.122529

In [84]:
category_analysis = category_analysis.sort_values(
    "Total_Revenue",
    ascending=False
)

print(category_analysis)

             Total_Revenue  Total_Quantity  Average_Price  Average_Rating
Category
Electronics         145500              93    1677.419355        3.953601
Clothing            124614              86    1529.769231        3.928488
Home                 54822              78     749.000000        4.122529
Books                45692              58     791.105263        3.914749

In [85]:
best_product = data.groupby("Product")["Revenue"].sum().idxmax()

print("Best Product:", best_product)

Best Product: Hoodie

In [86]:
best_category = data.groupby("Category")["Revenue"].sum().idxmax()

print("Best Category:", best_category)

Best Category: Electronics

In [87]:
best_city = data.groupby("City")["Revenue"].sum().idxmax()

print("Best City:", best_city)

Best City: Bangalore

In [88]:
print("========== E-COMMERCE SALES SUMMARY ==========")

print("Total Revenue:", data["Revenue"].sum())

print("Total Quantity Sold:", data["Quantity"].sum())

print("Average Order Value:", data["Revenue"].mean())

print("Average Rating:", data["Rating"].mean())

print("Best Product:", data.groupby("Product")["Revenue"].sum().idxmax())

print("Best Category:", data.groupby("Category")["Revenue"].sum().idxmax())

print("Best City:", data.groupby("City")["Revenue"].sum().idxmax())

print("Most Used Payment Method:", data["Payment_Method"].value_counts().idxmax())

========== E-COMMERCE SALES SUMMARY ==========
Total Revenue: 370628
Total Quantity Sold: 315
Average Order Value: 3706.28
Average Rating: 3.980232558139534
Best Product: Hoodie
Best Category: Electronics
Best City: Bangalore
Most Used Payment Method: Cash on Delivery